server:
  port: 8080
#\u6570\u636E\u5E93\u914D\u7F6E
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.105.73.76:3306/house?serverTimezone=UTC&characterEncoding=UTF8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd

mybatis-plus:
  mapper-locations: classpath*:com/ddhouse/house/mapper/**/*.xml
  type-aliases-package: com.ddhouse.house


